# Generated by Django 5.0.3 on 2024-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_web', '0003_dataset_description_dataset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
