# Generated by Django 5.0.3 on 2024-03-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('texto', models.CharField(max_length=300)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha_creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendapersonal.entrada')),
            ],
        ),
    ]
